package com.crispim.coverspin

object Constants {
    const val APP_NAME = "CoverSpin"

    // SharedPreferences Keys
    const val PREF_KEY_ROTATION_ENABLED = "IS_ROTATION_ENABLED"
    const val PREF_KEY_GESTURE_BUTTON_ENABLED = "GESTURE_BUTTON_ENABLED"
    const val PREF_KEY_LOG_LEVEL = "LOG_LEVEL"
    const val PREF_KEY_KEEP_SCREEN_ON = "KEEP_SCREEN_ON_ENABLED"
    const val PREF_KEY_ROTATION_MODE = "ROTATION_MODE"
    const val PREF_KEY_ANIMATION_TYPE = "ANIMATION_TYPE"
    const val PREF_KEY_ANIMATION_DURATION = "ANIMATION_DURATION"
    const val PREF_KEY_GESTURES_ENABLED = "GESTURES_ENABLED"
    const val PREF_KEY_HAPTIC_FEEDBACK = "HAPTIC_FEEDBACK"
    const val PREF_KEY_AUTO_START_ON_BOOT = "AUTO_START_ON_BOOT"
    const val PREF_KEY_BATTERY_OPTIMIZATION_DISABLED = "BATTERY_OPTIMIZATION_DISABLED"

    // Default Values
    const val SHOWING_GESTURE_BUTTON_MS = 2000
    const val SHOWING_TOAST_MS = 3000
    const val DEFAULT_ANIMATION_DURATION_MS = 300
}
